<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /home/rainbow/kode/transit/static/models/metro.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  // type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export let color: string;

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
    }
    materials: {
      Skin: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/metro.glb')

  let skin2: THREE.MeshStandardMaterial
  $: if ($gltf) {
    skin2 = $gltf.materials.Skin.clone()
    skin2.color.set(color)
  }

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    {#if skin2}
      <T.Mesh geometry={gltf.nodes.Cube.geometry} position={[0, 1, 2]}>
        <T is={skin2}/>
      </T.Mesh>
    {/if}
    <!-- <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials.Skin} position={[0, 1, 0]} /> -->
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
