<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 /home/rainbow/kode/transit/static/models/norreport.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Plane: THREE.Mesh
      Plane001: THREE.Mesh
      Plane002: THREE.Mesh
    }
    materials: {
      ['Skin.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/norreport.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Plane.geometry} material={gltf.materials['Skin.001']} scale={[5, 1, 25]} />
    <T.Mesh
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.nodes.Plane001.material}
      position={[-10, 11, -52]}
      scale={[1, 1, 2]}
    />
    <T.Mesh geometry={gltf.nodes.Plane002.geometry} material={gltf.nodes.Plane002.material} position={[-11, 11, -73]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
